apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appmint-form-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - forms.appmint.app
    secretName: appmint-form-tls
  rules:
  - host: forms.appmint.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appmint-form-service
            port:
              number: 80
