name: Deploy Image to Kubernetes

on:
  workflow_run:
    workflows: [Publish Docker image]
    types:
      - completed

env:
  ORG_ID: "default"
  DOCKER_HUB: "jaclight/fundu"
  SITE_NAME: "appmint-form"  
   
jobs:
  push_to_registry:
    name: Deploy Image To Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3    

      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
                
      - name: Deploy Image
        run: |
          export IMAGE_NAME=$IMAGE_NAME
          echo Image Name: ${IMAGE_NAME} for org ${ORG_ID}, site: ${SITE_NAME}
          
          # Apply deployment and service
          envsubst < ./.github/k8/deploy.yaml | kubectl --kubeconfig=./.github/k8/auth.yaml apply -f -
          
          # Apply ingress
          kubectl --kubeconfig=./.github/k8/auth.yaml apply -f ./.github/k8/ingress.yml
        shell: bash
        env:
          IMAGE_NAME: jaclight/fundu:appmint-form-${{steps.package-version.outputs.current-version}}
